export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const SHOP_ROUTE = '/'
export const CART_ROUTE = '/cart'
export const ITEM_ROUTE = '/item'